# Generated by Django 5.0.4 on 2024-10-28 16:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem_usuario', models.TextField()),
                ('resposta_chatbot', models.TextField()),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('emocao', models.CharField(blank=True, max_length=50, null=True)),
                ('intensidade_emocao', models.IntegerField(blank=True, null=True)),
                ('intencao_usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_interacao', models.CharField(choices=[('informativa', 'Informativa'), ('suporte_emocional', 'Suporte Emocional'), ('consulta', 'Consulta'), ('outro', 'Outro')], default='outro', max_length=50)),
                ('duracao_resposta', models.DurationField(blank=True, null=True)),
                ('contexto_conversa', models.JSONField(blank=True, null=True)),
                ('acompanhamento', models.BooleanField(default=False)),
                ('avaliacao_usuario', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
                'ordering': ['-data_hora'],
            },
        ),
    ]
